== Background

Currently (as of 9/2020) there is no turnkey solution for integrating Gitea webhooks with Tekton. A couple of custom approaches have been described such as the creation of a custom webhook endpoint.  Gitea webhook actions are sent to this endpoint, parsed, and then the appropriate Tekton objects are created (e.g., `pipelinerun`, `pipeline` objects). An example implemented in Go is described here https://medium.com/swlh/gitea-webhook-for-tekton-pipelines-9b621cb9c206

The recommended approach is to use Tekton Triggers which provide a more generic framework to accomplish the approach described above.

== Tekton Triggers

Tekton Triggers (https://github.com/tektoncd/triggers) is an additional project that creates four kubernetes custom resource definitions (CRDs), described briefly below:


=== TriggerTemplate

A template defining the Tekton objects to be created when a trigger is initiated. As an example on a *Gitea push to branch* event the followiing *TriggerTemplates* can be defined:

* Create a `pipeline` object specific to this branch (e.g., the branch name is included in the pipeline's name)
* Create a `pipelinerun` object to start a new run of this branch.

=== TriggerBinding

Defines the connection between an event (CI tool webhook receipt) and parameters that can then be passed to `TriggerTemplate`s.  Supports an expression syntax (JSONPath) for extracting parameters from a JSON payload.

Example:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
```

=== ClusterTriggerBinding

Identical to `TriggerBinding`, except it is scoped at the cluster level instead of the project level.

=== EventListener

Connects a `TriggerBinding` with a `TriggerTemplate` based on an incoming HTTP event with a JSON payload (e.g. a CI tool webhook). There is some built-in support for GitHub and GitLab. Refer to https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md for additional information.


== Tekton Triggers and Gitea

Tekton Triggers can certainly be used to implement an approach for supporting Gitea webhooks with Tekton. There are, however, some drawbacks:

* The supporting objects (`TriggerTemplate`, `TriggerBinding` and `EventListener`) would need to be created for all Gitea events that are required
* These objects potentially need to be updated to stay in sync with the Gitea API
* This solution would need to be maintained in parallel with the Jenkins solution, and solutions for other CI tools

At this time the effort for implementing the Tekton Trigger based solution may be better spent creating a more generic solution that is applicable to all CI tools. That solution may leverage some of the components provided by Tekton Triggers.
