apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
  volumeMode: Filesystem
