apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-repositories
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2
  volumeMode: Filesystem
