= OpenShift Pipelines features:

 * Standard CI/CD pipeline definition based on Tekton
 * Build images with Kubernetes tools such as S2I, Buildah, Buildpacks, Kaniko, etc
 * Deploy applications to multiple platforms such as Kubernetes, serverless and VMs
 * Easy to extend and integrate with existing tools
 * Scale pipelines on-demand
 * Portable across any Kubernetes platform
 * Designed for microservices and decentralized teams
 * Integrated with the OpenShift Developer Console


== Concepts

Tekton defines a number of Kubernetes custom resources as building blocks in order to standardize pipeline concepts and provide a terminology that is consistent across CI/CD solutions. 
These custom resources are an extension of the Kubernetes API that let users create and interact with these objects using kubectl and other Kubernetes tools.

The custom resources needed to define a pipeline are listed below:

  * `Task`: a reusable, loosely coupled number of steps that perform a specific task (e.g. building a container image)
  * `Pipeline`: the definition of the pipeline and the Tasks that it should perform
  * `PipelineResource`: inputs (e.g. git repository) and outputs (e.g. image registry) to and out of a pipeline or task
  * `TaskRun`: the execution and result of running an instance of task
  * `PipelineRun`: the execution and result of running an instance of pipeline, which includes a number of TaskRuns
Tekton Architecture

In short, in order to create a pipeline, one does the following:

  * Create custom or install existing reusable `Tasks`
  * Create a `Pipeline` and `PipelineResources` to define your application's delivery pipeline
  * Create a `PipelineRun` to instantiate and invoke the pipeline
  
== Install OpenShift Pipelines  
 
OpenShift Pipelines is provided as an add-on on top of OpenShift that can be installed via an operator available in
the OpenShift OperatorHub.

To start, make sure you are on the **Administrator** perspective:

Go to **Operators > OperatorHub** in the Web Console. You can see the list of available operators for OpenShift provided by
Red Hat as well as a community of partners and open-source projects.

In the search bar where it says `Filter by keyword...`, type OpenShift Pipelines to find the **OpenShift Pipelines Operator**:

OpenShift OperatorHub

Click on **OpenShift Pipelines Operator**, Continue, and then **Install**:

Leave the default settings and click on **Subscribe** in order to subscribe to the installation and update channels:

After clicking **Subscribe**, you will be taken to the **Installed Operators** page. If you do not see the **OpenShift 
Pipelines Operator**, simply wait a moment while the **OpenShift Pipelines Operator** finishes installation:

That's all. The operator now installs OpenShift Pipelines on the cluster.

You can confirm the following by checking tekton-pipelines and tekton-triggers pods with `Running` state in `openshift-
pipelines` namespace. If so, openshift-pielines have been installed on your cluster.

