= Keycloak
TSSC Keycloak Deployment Documentation

== Deployment


=== Install OpenShift Client 
If you do not have the oc client installed, refer to the following documentation

https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html=installing-the-cli

=== Login to OpenShift
Login to OCP w/ an account that has cluster admin level permissions

```
oc login
```


=== Create Keycloak OpenShift Project
Create an OpenShift Project for Keycloak (Can be configured to any name)

```
oc new-project keycloak
```

=== Clone this Repository
To clone this repository you must first have git installed. to install git follow the instructions https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[here]. 

Once git is installed, clone the repo using either SSH:

```
git clone git@github.com:rhtconsulting/tssc-infra.git
```

or HTTPS:

```
git clone https://github.com/rhtconsulting/tssc-infra.git
```

=== Deploy Keycloak

```
cd tssc-infra/docs/keycloak
```
```
oc create -R -f ./ 
```

That's it, you're done, keycloak is up and running! Login an give it a shot.
**Note:** The initial admin login for this instance is a username of `keycloak` and password of `password`. It is recommended this gets changed after the first login.
