apiVersion: v1
data:
  keycloak.sh: |
    #!/usr/bin/env bash
    set -o errexit
    set -o nounset
    exec /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0  -c standalone.xml
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  name: keycloak-sh
