= Start and stop Amazon EC2 instances at regular intervals using Lambda
How To guide for configuring EC2 instances to automatically stop & start

== Configuration

=== Login to AWS Console

https://console.aws.amazon.com/

Select Region: US West (Oregon) us-west-2 

=== Create IAM Policy

Select “Services” -> “IAM”

Select “Policies” on left menu

Select “Create Policy” blue button

Select “JSON” tab

Insert code
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:*:*:*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:Start*",
        "ec2:Stop*"
      ],
      "Resource": "*"
    }
  ]
}
```
Select “Review Policy” blue button

In Name field:  IAM-Policy-Start-Stop-Lambda-Function 

Select “Create Policy” blue button


=== Create IAM Role


Select “Services” -> “IAM”

Select “Roles” on left menu

Select “Create role” blue button

Select "AWS service" box

Select "Lambda" in the "Choose a use case" section Select "Next: Permissions"

Select "IAM-Policy-Start-Stop-Lambda-Function"

Select "Next: Tags" blue button

Select "Next: Review" blue button

Input Role Naem:  "IAM-Role-Lamdba"

Select "Create role" blue button


=== Create Lambda functions that stop your EC2 instances

Select "Services" -> "Lambda"

Select "Functions" on left menu

Select "Create function" orange button

Select "Author from scratch"

Input Function Name: "Lambda-Function-Stop-EC2"

Select "Python 3.7" Runtime

Expand "Choose or create an execution role"

Select "Use an existing role"

Input Existing Role:  "IAM-Role-Lamdba"

Select "Creation Function" orange button

Insert Code in "lambda function" editor
```
import boto3
region = 'us-west-2'
instances = ['i-01654f9248e26d288', 'i-05b521e423d06ef9c', 'i-0737b78834c9c7c47', 'i-08873d2a77c9b5be1', 'i-0bef1ec33c65b81b0', 'i-0bef1ec33c65b81b0'i-0c3be84f087ebd1ee
]
ec2 = boto3.client('ec2', region_name=region)

def lambda_handler(event, context):
    ec2.stop_instances(InstanceIds=instances)
    print('stopped your instances: ' + str(instances))
```
Under Basic settings, set Timeout to 30 seconds.

Select "Save" orange button


=== Create Lambda functions that start your EC2 instances

Select "Services" -> "Lambda"

Select "Functions" on left menu

Select "Create function" orange button

Select "Author from scratch"

Input Function Name: "Lambda-Function-Start-EC2"

Select "Python 3.7" Runtime

Expand "Choose or create an execution role"

Select "Use an existing role"

Input Existing Role:  "IAM-Role-Lamdba"

Select "Creation Function" orange button

Insert Code in "lambda function" editor
```
import boto3
region = 'us-west-2'
instances = ['i-01654f9248e26d288', 'i-05b521e423d06ef9c', 'i-0737b78834c9c7c47', 'i-08873d2a77c9b5be1', 'i-0bef1ec33c65b81b0', 'i-0bef1ec33c65b81b0'i-0c3be84f087ebd1ee
]
ec2 = boto3.client('ec2', region_name=region)

def lambda_handler(event, context):
    ec2.start_instances(InstanceIds=instances)
    print('started your instances: ' + str(instances))
```
Under Basic settings, set Timeout to 30 seconds.
Select "Save" orange button


=== Create rules that trigger your Lambda stop function

Select "Services" -> "Cloud Watch"

In the left navigation pane, under Events, choose Rules

Choose Create rule

Under Event Source, choose Schedule

Select Cron Expression

Input:  0 2 * * ? *

Under Targets, choose Add target.

Choose Lambda function

For Function, select "Lamba-Function-Stop-EC2"

Select "Configure details" blue button

Under Rule definition, Input Name:  "CW-Stop-EC2"

Select State: "Enabled"

Select "Create Rule" blue button




=== Create rules that trigger your Lambda stop function

Select "Services" -> "Cloud Watch"

In the left navigation pane, under Events, choose Rules

Choose Create rule

Under Event Source, choose Schedule

Select Cron Expression

Input:  0 12 * * ? *

Under Targets, choose Add target.

Choose Lambda function

For Function, select "Lamba-Function-Start-EC2"

Select "Configure details" blue button

Under Rule definition, Input Name:  "CW-Start-EC2"

Select State: "Enabled"

Select "Create Rule" blue button
