= Jenkins

== Prerequisites

* The installation below will leverage OpenShift OAuth, and therefore it is recommended, if you wish to leverage OpenShift integrated Keycloak SSO, that Keycloak is deployed before performing these steps.

== Deployment (Day 0)

=== By Template
```
JENKINS_PROJECT_NAME=jenkins
JENKINS_NAME=jenkins
JENKINS_SERVICE_NAME=jenkins
JENKINS_MEMORY_LIMIT='4Gi'
JENKINS_VOLUME_CAPACITY='20Gi'
JENKINS_WORKERS_IMAGES_UID=1001

echo
echo "Create the project (${JENKINS_PROJECT_NAME}) for Jenkins to reside in"
oc new-project ${JENKINS_PROJECT_NAME}

echo
echo "Deploy Jenkins via the template"
oc process --namespace=openshift jenkins-persistent-monitored NAME=${JENKINS_NAME} JENKINS_SERVICE_NAME=${JENKINS_SERVICE_NAME} MEMORY_LIMIT=${JENKINS_MEMORY_LIMIT} VOLUME_CAPACITY=${JENKINS_VOLUME_CAPACITY} | oc create -f -

echo
echo "Create an SCC that can use the UID (${JENKINS_WORKERS_IMAGES_UID}) that the jenkins workers use"
echo "
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: TODO
  name: run-as-user-${JENKINS_WORKERS_IMAGES_UID}
runAsUser:
  type: MustRunAsRange
  uidRangeMax: ${JENKINS_WORKERS_IMAGES_UID}
  uidRangeMin: ${JENKINS_WORKERS_IMAGES_UID}
seLinuxContext:
  type: MustRunAs" | oc create -f -

echo
echo "Create role that can use the new SCC"
__JENKINS_CUSTOM_ROLE_NAME=${JENKINS_PROJECT_NAME}-scc-run-as-user-${JENKINS_WORKERS_IMAGES_UID}
oc create role ${__JENKINS_CUSTOM_ROLE_NAME} --verb=use --resource=scc --resource-name=run-as-user-${JENKINS_WORKERS_IMAGES_UID} --namespace=${JENKINS_PROJECT_NAME}

echo
echo "Create RoleBinding for Jenkins ServiceAccount (${JENKINS_SERVICE_NAME}) to the custome Role (${__JENKINS_CUSTOM_ROLE_NAME}) to allow Jenkins to spin up Jenkins Workers using the custom UID (${JENKINS_WORKERS_IMAGES_UID})"
oc create rolebinding ${JENKINS_PROJECT_NAME}-${JENKINS_SERVICE_NAME}-sa-run-as-user-${JENKINS_WORKERS_IMAGES_UID} --role=${__JENKINS_CUSTOM_ROLE_NAME} --serviceaccount=${JENKINS_PROJECT_NAME}:${JENKINS_SERVICE_NAME}

echo
echo "Jenkins URL"
echo "https://$(oc get route ${JENKINS_SERVICE_NAME} -o=jsonpath='{.spec.host}')"
```

=== By Opertator
TBD

== Post Deployment (Day 1)

=== By Template

==== Update Jenkins plugins
1. log into the Jenkins UI
2. `Manage Jenkins` -> `Manage Plugins` -> `Updates`
3. Scroll to bottom
4. Click - Select: `Compatible`
5. `Download Now and install after restart`
6. Check - `Restart Jenkins when installation is complete and no jobs are running`
7. Wait for restart

==== Install Jenkins plugins
1. log into the Jenkins UI
2. `Manage Jenkins` -> `Manage Plugins` -> `Availabe`
3. Check:
   * AnsiColor
   * Gitea
4. Click - `Download now and install after restart`
5. Check - `Restart Jenkins when installation is complete and no jobs are running`
6. Wait for restart

=== By Operator
TBD

== Configure Updates/Upgrades/Backups (Day 2)
TODO

== Onboard Application(s) onto TSSC (Day 3)

=== Configure Jenkins to Scan a Gitea Org

==== By Template

===== Create a Service Account in Gitea for Jenkins to use to access the Organization

====== OpenID Identity Provider Service Account
TBD

===== Manual Local Service Account
1. Log into Gitea as administrator
2. Upper Right Drop Down -> Site Administration
3. User Accounts
4. Create User Account
  * Username: sa-${JENKINS_PROJECT_NAME}-${JENKINS_SERVICE_NAME}-${GITEA_ORG_NAME}
  * Email: whatever
    * NOTE: not sure what if anything this would get used for
  * Password: Randomly Generate one and save it someplace
  * Require user to change password (recommended): UN-check
5. Organziations
6. Edit the organization to scan for projects to run in Jenkins
  - in tssc integration this is the `tssc-references` org
7. New Team
  * Team Name: service-accounts
  * Repository acess: All repositories
  * Permissions: Read Access
  * Allow Access to Repository Sections
    - Code
    - Issues
    - Pull Requests
    - Releases
8. Add Team Member
  * User created in step 4
9. Logout of Gitea as administrator
10. log into Gitea as service account
11. Upper Right Drop Down -> Settings
12. Applications
  * Token Name: sa-${JENKINS_PROJECT_NAME}-${JENKINS_SERVICE_NAME}
  * Generate Token
  * record the token temporary for use in future step as ${GITEA_JENKINS_SA_TOKEN}

===== Connect Jenkins to Gitea

1. log into the Jenkins UI
2. `Manage Jenkins` -> `Configure System`
3. `Gitea Servers` -> `Add` -> `Gitea Server`
  * Name: TSSC Gitea (Or whatever)
  * Server URL: http://gitea.gitea.svc.cluster.local:3000
    - NOTE: have tried using public route but had troubles in TSSC infra environment, that may just be a problem with the certs or something in that environment, but hitting the service directly seems to work, but in the TSSC infra environment currently no NetworkPolicies are in place. With a "sane" NetworkPolicy structure the jenkins project woulnd't be able to directly hit the gitea service, so this is an issue that has to be sorted in a more "sanly" built infra.
  * Advanced: Alias URL: http://gitea.gitea.svc.cluster.local:3000
    - VERIFY: that below Server URL Jenkins shows `Gitea Versin: *.*.*` and not an error
    - if specifying the non public URL in the `Server URL` then be sure to use the actual public URL here

===== Create Gitea Org in Jenkins

1. log into the Jenkins UI
2. `New Item`
  * Name: GITEA_ORG_NAME
    - this should be whatever the org name is in gitea, for tssc intgegration enviornment this is `tssc-references`
  * Gitea Organization
3. Click - OK
4. Configure the Gitea Org Item
  * Server: Select the name that was created in the `Connect Jenkins to Gitea` step
  * Credentials: Add then select
    - Domain: whatever
    - Kind: Gitea Personal Access Token
    - Token: ${GITEA_JENKINS_SA_TOKEN}
      * from step `Create a Service Account in Gitea for Jenkins to use to access the Organization`
    - ID: ${GITEA_SA_NAME}
      * from step `Create a Service Account in Gitea for Jenkins to use to access the Organization`
  * Owner: ${GITEA_ORG_NAME}
    - this needs to match the org name in gitea that the service account was given access to that you want to scan projects of
  * Behaviors
    - Discovery Branches
      * Strategy: TBD
        - Currently we are using `All Branches` but that was just a guess, we need to do some expirmentation to figure out what the right setting here is.
        - currently with all branches we get duplicate pipelines for both the branch and PR for branch, need to try and get it down so that there isn't duplication and decide what the default opinion is
        - thinking that maybe `Only branches thgat are also files as PRs` may make snese but then you run into problem that you can't create a PR for a branch that is the same as the branch (`main`) you are merging into, so then you get a chicken/egg problem of getting a dev environment when you first branch
    - Discover pull requests from origion
      * Strategy: `The current pull reuqest revision`
    - Discover pull requests from forks
      * Strategy: `The current pull reuqest revision`
   - Add
     * `Check out to matching local branch`
  * Project Recognizers
    - Pipeline Jenkinsfile
      * Script Path: `cicd/Jenkins/Jenkinsfile`
        - NOTE: this is what the TSSC integration reference prjoejcts currently use, update to be wherever your apps store Jenkinsfiles
  * Save

===== Created Jenkins Crednetial with SOPS decryption information
It is assumed that the applciations using the TSSC will have some of their configuraiton encrypted using SOPS and thus Jenkins will need a way to decrypt that.

As of this writing (9/23/20) the Jenkins Reference Pieplines assume a PGP key for uncrypting SOPS information. This is step to add that key.

1. Log into Jenkins UI
2. open the Gitea Org item
3. Credentials
4. Open the Stores scoped to (gita org item)
5. Global Credentials (unrestricted)
6. Add Credentials
  * Kind: Secret file
  * File: upload private PGP key that is added to the SOPS configurate of any encrypted TSSC configuration
  * ID: must match the value of `credentialIDsopsPGPKey` passed from the gita projects `Jenkinsfile` to the https://github.com/rhtconsulting/tssc-jenkins-library pipeline function being used.
    - SEE: https://github.com/rhtconsulting/tssc-jenkins-library/blob/main/vars/pipelineJava8.groovy#L75-L81
    - EXAMPLE: http://gitea.tssc.rht-set.com/tssc-references/tssc-reference-app-quarkus-rest-json/src/branch/main/cicd/Jenkins/Jenkinsfile#L11
  * OK

==== By Operator
TBD

=== Configure Applciation TSSC configuration and Jenkins so Jenkins can decrypt SOPS encrypted TSSC configuration

==== Create PGP key for Jenkins to be able to use to decrypt SOPS encrypted TSSC config

* GIT_REPO_NAME_USING_TSSC
  - name of the git repo that will contain TSSC configuration file(s) that will have this PGP key
    added to the list of PGP keys that can decrypt the TSSC configuration
* JENKINS_GPG_KEY_REAL_NAME: ${JENKINS_PROJECT_NAME}-${JENKINS_SERVICE_NAME}-${GIT_REPO_NAME_USING_TSSC}

1. generate the new private key: `gpg --generate-key`
  * Real name: ${JENKINS_GPG_KEY_REAL_NAME}
  * Email address: <blank>
  * Okay
  * no passphrase
  * <yes, protection is not needed>
  * no passphrase
  * <yes, protection is not needed>
2. record the new fingerprint as ${JENKINGS_GPG_FINGERPRINT}
3. export the private key: `gpg --export-secret-keys ${JENKINGS_GPG_FINGERPRINT} > /tmp/${JENKINS_GPG_KEY_REAL_NAME}.key`

==== Import Jenkins PGP key as Jenkins credential

* JENKINS_CREDNETIAL_ID_SOPS_PGP_KEY: ${JENKINS_GPG_KEY_REAL_NAME}-pgp-private-key

1. Jenkins -> Gitea Org -> Credentials
2. Stores scoped to ${GITEA_ORG} -> ${GITEA_ORG}
3. Global credentials (unrestricted)
4. Add Credential
  * Kind: `Secret file`
  * File: (`/tmp/${JENKINS_GPG_KEY_REAL_NAME}.key`)
  * ID: ${JENKINS_CREDNETIAL_ID_SOPS_PGP_KEY}
  * OK
5. Delete local copy of private key, (AKA, throw away the key):
  * `rm -f /tmp/${JENKINS_GPG_KEY_REAL_NAME}.key`
  * `gpg --delete-secret-key ${JENKINGS_GPG_FINGERPRINT}`
    * answer yes to the 5000 times you get asked

==== Add the Jenkins PGP key to the SOPS encrypted TSSC configuration
1. checkout out the application that is going to use the TSSC
2. `sops --in-place --rotate --add-pgp ${JENKINGS_GPG_FINGERPRINT}` ${PATH_TO_APP_TSSC_CONFIG_FILE_ENCRYPTED_WITH_SOPS}
  * NOTE: you need to have a private key in your gpg keystore that has access to decrypt the sops encrypted TSSC config file
  * IMPORTANT: to add a new key to a SOPS encrypted file you MUST rotate (`--rotate`) the SOPS key, which means all values will be re-encrypted
3. commit and push the changes

==== Update the Jenkinsfile with the Jenkins Crednetial ID for the PGP key
1. checkout out the application that is going to use the TSSC
2. edit the Jenkinsfile
  * for whichever jenkins pipeline function is being called (AKA: `pipelineJava8`) specify
    the `credentialIDsopsPGPKey` parameter to equal ${JENKINS_CREDNETIAL_ID_SOPS_PGP_KEY}
3. commit and push the changes
