---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-apps-tssc-rht-set-com
  namespace: openshift-ingress
spec:
  secretName: router-certs
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - tssc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - '*.apps.tssc.rht-set.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
