---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: itewk+letsencrypt@redhat.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "rht-set.com"
      dns01:
        route53:
          region: us-west-2
          accessKeyID: AKIAQY43FAYYF22M5SEJ
          hostedZoneID: Z0225062KQFBU1V5V7WV
          secretAccessKeySecretRef:
            name: aws-route53-creds-ocp-tssc-infra-cert-manager
            key: ocp-infra-cert-manager-aws-secret-access-key.txt.dec
